# Generated by Django 3.1.6 on 2021-04-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquityTicker',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatSymbol',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquityProfileCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('annual_return', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('annual_volatility', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('sharpe_ratio', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('asset_beta', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.equityticker')),
            ],
        ),
        migrations.CreateModel(
            name='EquityMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.equityticker')),
            ],
        ),
        migrations.CreateModel(
            name='EquityCorrelationCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('correlation', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('ticker_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_1', to='data.equityticker')),
                ('ticker_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_2', to='data.equityticker')),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('statistic', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='data.statsymbol')),
            ],
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.equityticker')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cryptoticker')),
            ],
        ),
    ]
