# Generated by Django 3.0.8 on 2021-02-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('statistic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquityTicker',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquityMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.EquityTicker')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.CryptoTicker')),
            ],
        ),
    ]
