# Generated by Django 3.1.6 on 2021-03-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityProfileCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('annual_return', models.DecimalField(decimal_places=6, max_digits=20)),
                ('annual_volatility', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sharpe_ratio', models.DecimalField(decimal_places=6, max_digits=20)),
                ('asset_beta', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.equityticker')),
            ],
        ),
    ]
