# Generated by Django 3.0.8 on 2021-02-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.EquityTicker')),
            ],
        ),
    ]
