# Generated by Django 3.1.6 on 2021-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_equityprofilecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityprofilecache',
            name='annual_return',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='equityprofilecache',
            name='annual_volatility',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='equityprofilecache',
            name='asset_beta',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='equityprofilecache',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
