# Generated by Django 3.1.6 on 2021-03-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210324_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityCorrelationCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('correlation', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('ticker_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_1', to='data.equityticker')),
                ('ticker_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_2', to='data.equityticker')),
            ],
        ),
    ]
