version: 2.1

commands:
  install:
    description: install build dependencies
    steps:
      - run:
          name: dependency installation
          command: pip install twine setuptools build
  build:
    description: compress and build python package
    steps:
      - run:
          name: artifact build
          command: python -m build
  upload:
    description: upload package artifacts to PyPi
    steps:
      - run:
          name: artifact upload
          command: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  push:
    description: push new version number to GitHub
    steps:
        - run: 
            name: push version
            command: |
              echo "TODO"

  
jobs:
  pypi_micro_update:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install
      - run:
          name: iterate micro version
          command: |
            python ./scripts/circleci/iterate_version.py micro
      - build
      - upload
      - push

  pypi_minor_update:
    docker: 
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install
      - run:
          name: iterate minor version
          command: | 
            python ./scripts/circleci/iterate_version.py minor
      - build
      - upload
      - push

  pypi_major_update:
    docker: 
      - image: cimg/python:3.9.6
    steps:
      - checkout 
      - install
      - run:
          name: iterate major version
          command: |
            python ./scripts/circleci/iterate_version.py major
      - build
      - upload
      - push

workflows:
  version: 2
  build_and_push:
    jobs:
      - pypi_micro_update:
          filters:
            branches:
              only:
                - pypi/micro-update
      - pypi_minor_update:
          filters: 
            branches:
              only:
                - pypi/minor-update
      - pypi_major_update:
          filters:
            branches:
              only:
                - pypi/major-update