#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..
DOCS_DIR=$PROJECT_DIR/docs
APP_DIR=$PROJECT_DIR/src/scrilla

if [ -d $DOCS_DIR ]
then
    rm -r $DOCS_DIR/coverage/*
fi

if [ "$1" == "circleci" ]
then
    echo "on circleci"
else
    cd $PROJECT_DIR
    coverage run -m pytest
    coverage html

    rm $DOCS_DIR/coverage/.gitignore
fi

